# -*- coding: utf-8 -*-
"""BiasEvalPipelineRunner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kqaiO7DSqIUAYYqyuYMbeiBR8v-XDcRS
"""

from EvalBiasPipeline import biasEvalPipeline

DATA_TARGET_POS = 1
DATA_TARGET_CHUNK = 2
DATA_TARGET_NER = 3


# religion debiased w2vs
WV_PAIRS = [
    ["/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/hard-debiasing/religion_default_biasedEmbeddingsOut.w2v",
     "/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/hard-debiasing/religion_default_hardDebiasedEmbeddingsOut.w2v"],
    ["/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/mean/religion_mean_biasedEmbeddingsOut.w2v",
     "/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/mean/religion_mean_hardDebiasedEmbeddingsOut.w2v"],
    ["/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/sum/religion_sum_biasedEmbeddingsOut.w2v",
     "/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/sum/religion_sum_hardDebiasedEmbeddingsOut.w2v"],
    ["/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/poly/religion_poly_biasedEmbeddingsOut.w2v",
     "/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Debiasing/output/religion_evalset/poly/religion_poly_hardDebiasedEmbeddingsOut.w2v"],
    ]

NER_PATH = "/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Downstream/data/conll2003"

logFile = open("/content/drive/MyDrive/DebiasMulticlassWordEmbedding-master/Downstream/out/log_gender.txt", "w")
for bwv, dbwv in WV_PAIRS:
    for target in [DATA_TARGET_POS, DATA_TARGET_CHUNK, DATA_TARGET_NER]:
        print("======================================================")
        print("\t", bwv, "\n\t", dbwv, "\n\t", target)
        biasEvalPipeline(bwv, dbwv, NER_PATH, target, logFile=logFile, verbose=False, results=True)
logFile.close()

